import { BookInfo } from "./card";

export var books:BookInfo[] = [
    {type: 'intro',
    name: '汇智网 Node.js 课程',
    href: 'http://www.hubwiz.com/course/?type=nodes'},
    {type: 'intro',
    name: '快速搭建 Node.js 开发环境以及加速 npm',
    href: 'http://fengmk2.com/blog/2014/03/node-env-and-faster-npm.html'},
    {type: 'intro',
    name: 'Node.js 包教不包会',
    href: 'https://github.com/alsotang/node-lessons'},
    {type: 'intro',
    name: 'ECMAScript 6入门',
    href: 'http://es6.ruanyifeng.com/'},
    {type: 'intro',
    name: '七天学会NodeJS',
    href: 'https://github.com/nqdeng/7-days-nodejs'},
    {type: 'intro',
    name: 'Node入门-一本全面的Node.js教程',
    href: 'http://www.nodebeginner.org/index-zh-cn.html'},
    {type: 'resource',
    name: 'node weekly',
    href: 'http://nodeweekly.com/issues'},
    {type: 'resource',
    name: 'node123-node.js中文资料导航',
    href: 'https://github.com/youyudehexie/node123'},
    {type: 'resource',
    name: 'A curated list of delightful Node.js packages and resources',
    href: 'https://github.com/sindresorhus/awesome-nodejs'},
    {type: 'resource',
    name: 'Node.js Books',
    href: 'https://github.com/pana/node-books'},
    {type: 'celebrity',
    name: '名人堂',
    href: 'https://github.com/cnodejs/nodeclub/wiki/名人堂'},
];


